laktest_sources = []
laktest_dependencies = [lakcore_dep, dependency('threads')]

subdir('dsl')

laktestcore = static_library(
	'laktestcore',
	laktest_sources + [
		'codegen'/'cpp.cpp',
		'ebpf'/'ebpf.cpp',
		'ebpf'/'assembler.cpp',
		'ebpf'/'vm.cpp',
		'file'/'ebnf.cpp',
		'file'/'json.cpp',
		'file'/'nbt.cpp',
		'file'/'obj.cpp',
		'file'/'pnm.cpp',
		'file'/'tiff.cpp',
		'system'/'architecture.cpp',
		'algorithm.cpp',
		'alloc.cpp',
		'array.cpp',
		'bigint.cpp',
		'bit_count.cpp',
		'bit_field.cpp',
		'bit_reader.cpp',
		'bitflag.cpp',
		'bitset.cpp',
		'blob_search.cpp',
		'com_ptr.cpp',
		'compare.cpp',
		'const_string.cpp',
		'format.cpp',
		'functional.cpp',
		'integer_range.cpp',
		'macro_utils.cpp',
		'math.cpp',
		'memory.cpp',
		'numeric.cpp',
		'optional.cpp',
		'priority_queue.cpp',
		'ptr_intrin.cpp',
		'result.cpp',
		'runtime_type.cpp',
		'span_manip.cpp',
		'strconv.cpp',
		'string_literals.cpp',
		'test.cpp',
		'tokeniser.cpp',
		'trie.cpp',
		'type_pack.cpp',
		'unicode.cpp',
		'visit.cpp',
		'wide_math.cpp',
	],
	dependencies: laktest_dependencies,
)

laktestcore_dep = declare_dependency(
	link_whole: laktestcore,
)
