#include "lak/test.hpp"

#include "lak/array.hpp"
#include "lak/string_literals/view.hpp"

#include "lak/ebpf/ebpf.hpp"

BEGIN_TEST(ebpf)
{
	using namespace lak::ebpf;

	auto imm64 = instruction::make_load(lak::ebpf::register_t::R1, UINT64_MAX);
	auto load2 = instruction::make_load(
	  lak::ebpf::register_t::R1, 2, UINT32_MAX, UINT32_MAX);
	auto load6 = instruction::make_load(
	  lak::ebpf::register_t::R1, 6, UINT32_MAX, UINT32_MAX);

	lak::array<instruction> inst = {
	  imm64.first,
	  imm64.second,
	  instruction::make_load(lak::ebpf::register_t::R1, 1, UINT32_MAX),
	  load2.first,
	  load2.second,
	  instruction::make_load(lak::ebpf::register_t::R1, 3, UINT32_MAX),
	  instruction::make_load(lak::ebpf::register_t::R1, 4, UINT32_MAX),
	  instruction::make_load(lak::ebpf::register_t::R1, 5, UINT32_MAX),
	  load6.first,
	  load6.second,
	  instruction::make_load(opcode_load_store_size::DW,
	                         lak::ebpf::register_t::R1,
	                         lak::ebpf::register_t::R2,
	                         UINT16_MAX),
	  instruction::make_load(opcode_load_store_size::W,
	                         lak::ebpf::register_t::R1,
	                         lak::ebpf::register_t::R2,
	                         UINT16_MAX),
	  instruction::make_load(opcode_load_store_size::H,
	                         lak::ebpf::register_t::R1,
	                         lak::ebpf::register_t::R2,
	                         UINT16_MAX),
	  instruction::make_load(opcode_load_store_size::B,
	                         lak::ebpf::register_t::R1,
	                         lak::ebpf::register_t::R2,
	                         UINT16_MAX),

	  instruction::make_store(opcode_load_store_size::DW,
	                          lak::ebpf::register_t::R1,
	                          UINT16_MAX,
	                          lak::ebpf::register_t::R2),
	  instruction::make_store(opcode_load_store_size::W,
	                          lak::ebpf::register_t::R1,
	                          UINT16_MAX,
	                          lak::ebpf::register_t::R2),
	  instruction::make_store(opcode_load_store_size::H,
	                          lak::ebpf::register_t::R1,
	                          UINT16_MAX,
	                          lak::ebpf::register_t::R2),
	  instruction::make_store(opcode_load_store_size::B,
	                          lak::ebpf::register_t::R1,
	                          UINT16_MAX,
	                          lak::ebpf::register_t::R2),

	  instruction::make_store(opcode_load_store_size::DW,
	                          lak::ebpf::register_t::R1,
	                          UINT16_MAX,
	                          UINT32_MAX),
	  instruction::make_store(opcode_load_store_size::W,
	                          lak::ebpf::register_t::R1,
	                          UINT16_MAX,
	                          UINT32_MAX),
	  instruction::make_store(opcode_load_store_size::H,
	                          lak::ebpf::register_t::R1,
	                          UINT16_MAX,
	                          UINT32_MAX),
	  instruction::make_store(opcode_load_store_size::B,
	                          lak::ebpf::register_t::R1,
	                          UINT16_MAX,
	                          UINT32_MAX),

	  // :TODO: atomics

	  instruction::make_end16(opcode_alu_endian::TO_LE,
	                          lak::ebpf::register_t::R1),
	  instruction::make_end32(opcode_alu_endian::TO_BE,
	                          lak::ebpf::register_t::R2),
	  instruction::make_bswap64(lak::ebpf::register_t::R3),

	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::ADD,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::MUL,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::DIV,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make_sdiv(opcode_class_alu::ALU,
	                         lak::ebpf::register_t::R1,
	                         lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::MOD,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make_smod(opcode_class_alu::ALU,
	                         lak::ebpf::register_t::R1,
	                         lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::MOV,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make_movsx8(opcode_class_alu::ALU,
	                           lak::ebpf::register_t::R1,
	                           lak::ebpf::register_t::R2),
	  instruction::make_movsx16(opcode_class_alu::ALU,
	                            lak::ebpf::register_t::R1,
	                            lak::ebpf::register_t::R2),
	  instruction::make_movsx32(opcode_class_alu::ALU,
	                            lak::ebpf::register_t::R1,
	                            lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::ADD,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::MUL,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::DIV,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make_sdiv(opcode_class_alu::ALU64,
	                         lak::ebpf::register_t::R1,
	                         lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::MOD,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make_smod(opcode_class_alu::ALU64,
	                         lak::ebpf::register_t::R1,
	                         lak::ebpf::register_t::R2),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::MOV,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2),
	  instruction::make_movsx8(opcode_class_alu::ALU64,
	                           lak::ebpf::register_t::R1,
	                           lak::ebpf::register_t::R2),
	  instruction::make_movsx16(opcode_class_alu::ALU64,
	                            lak::ebpf::register_t::R1,
	                            lak::ebpf::register_t::R2),
	  instruction::make_movsx32(opcode_class_alu::ALU64,
	                            lak::ebpf::register_t::R1,
	                            lak::ebpf::register_t::R2),

	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::ADD,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::MUL,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::DIV,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make_sdiv(
	    opcode_class_alu::ALU, lak::ebpf::register_t::R1, UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::MOD,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make_smod(
	    opcode_class_alu::ALU, lak::ebpf::register_t::R1, UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU,
	                    opcode_alu::MOV,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::ADD,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::MUL,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::DIV,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make_sdiv(
	    opcode_class_alu::ALU64, lak::ebpf::register_t::R1, UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::MOD,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),
	  instruction::make_smod(
	    opcode_class_alu::ALU64, lak::ebpf::register_t::R1, UINT32_MAX),
	  instruction::make(opcode_class_alu::ALU64,
	                    opcode_alu::MOV,
	                    lak::ebpf::register_t::R1,
	                    UINT32_MAX),

	  instruction::make_jump16(UINT16_MAX),
	  instruction::make_agnostic_helper_call(UINT32_MAX),
	  instruction::make_local_call(UINT32_MAX),
	  instruction::make_specific_helper_call(UINT32_MAX),
	  instruction::make_exit(),

	  instruction::make(opcode_class_jump::JMP,
	                    opcode_jump::JEQ,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2,
	                    UINT16_MAX),
	  instruction::make(opcode_class_jump::JMP,
	                    opcode_jump::JGT,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2,
	                    UINT16_MAX),
	  instruction::make(opcode_class_jump::JMP,
	                    opcode_jump::JSET,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2,
	                    UINT16_MAX),
	  instruction::make(opcode_class_jump::JMP32,
	                    opcode_jump::JEQ,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2,
	                    UINT16_MAX),
	  instruction::make(opcode_class_jump::JMP32,
	                    opcode_jump::JGT,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2,
	                    UINT16_MAX),
	  instruction::make(opcode_class_jump::JMP32,
	                    opcode_jump::JSET,
	                    lak::ebpf::register_t::R1,
	                    lak::ebpf::register_t::R2,
	                    UINT16_MAX),

	  instruction::make(opcode_class_jump::JMP,
	                    opcode_jump::JEQ,
	                    lak::ebpf::register_t::R1,
	                    UINT16_MAX,
	                    UINT32_MAX),
	  instruction::make(opcode_class_jump::JMP,
	                    opcode_jump::JGT,
	                    lak::ebpf::register_t::R1,
	                    UINT16_MAX,
	                    UINT32_MAX),
	  instruction::make(opcode_class_jump::JMP,
	                    opcode_jump::JSET,
	                    lak::ebpf::register_t::R1,
	                    UINT16_MAX,
	                    UINT32_MAX),
	  instruction::make(opcode_class_jump::JMP32,
	                    opcode_jump::JEQ,
	                    lak::ebpf::register_t::R1,
	                    UINT16_MAX,
	                    UINT32_MAX),
	  instruction::make(opcode_class_jump::JMP32,
	                    opcode_jump::JGT,
	                    lak::ebpf::register_t::R1,
	                    UINT16_MAX,
	                    UINT32_MAX),
	  instruction::make(opcode_class_jump::JMP32,
	                    opcode_jump::JSET,
	                    lak::ebpf::register_t::R1,
	                    UINT16_MAX,
	                    UINT32_MAX),
	};

	lak::array<lak::u8string_view> expected = {
	  u8"LD    | DW    | IMM   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"LD    | W     | IMM   .dst=00 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,

	  u8"LD    | DW    | IMM   .dst=01 .src=01 .off=0x0000 .imm=0xFFFFFFFF"_view,

	  u8"LD    | DW    | IMM   .dst=01 .src=02 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"LD    | W     | IMM   .dst=00 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,

	  u8"LD    | DW    | IMM   .dst=01 .src=03 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"LD    | DW    | IMM   .dst=01 .src=04 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"LD    | DW    | IMM   .dst=01 .src=05 .off=0x0000 .imm=0xFFFFFFFF"_view,

	  u8"LD    | DW    | IMM   .dst=01 .src=06 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"LD    | W     | IMM   .dst=00 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,

	  u8"LDX   | DW    | MEM   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"LDX   | W     | MEM   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"LDX   | H     | MEM   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"LDX   | B     | MEM   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,

	  u8"STX   | DW    | MEM   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"STX   | W     | MEM   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"STX   | H     | MEM   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"STX   | B     | MEM   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,

	  u8"ST    | DW    | MEM   .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	  u8"ST    | W     | MEM   .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	  u8"ST    | H     | MEM   .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	  u8"ST    | B     | MEM   .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,

	  u8"ALU   | TO_LE | END   .dst=01 .src=00 .off=0x0000 .imm=0x00000010"_view,
	  u8"ALU   | TO_BE | END   .dst=02 .src=00 .off=0x0000 .imm=0x00000020"_view,
	  u8"ALU64 | BSWAP | END   .dst=03 .src=00 .off=0x0000 .imm=0x00000040"_view,

	  u8"ALU   | X     | ADD   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU   | X     | MUL   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU   | X     | DIV   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU   | X     | SDIV  .dst=01 .src=02 .off=0x0001 .imm=0x00000000"_view,
	  u8"ALU   | X     | MOD   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU   | X     | SMOD  .dst=01 .src=02 .off=0x0001 .imm=0x00000000"_view,
	  u8"ALU   | X     | MOV   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU   | X     | MOVSX .dst=01 .src=02 .off=0x0008 .imm=0x00000000"_view,
	  u8"ALU   | X     | MOVSX .dst=01 .src=02 .off=0x0010 .imm=0x00000000"_view,
	  u8"ALU   | X     | MOVSX .dst=01 .src=02 .off=0x0020 .imm=0x00000000"_view,
	  u8"ALU64 | X     | ADD   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU64 | X     | MUL   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU64 | X     | DIV   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU64 | X     | SDIV  .dst=01 .src=02 .off=0x0001 .imm=0x00000000"_view,
	  u8"ALU64 | X     | MOD   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU64 | X     | SMOD  .dst=01 .src=02 .off=0x0001 .imm=0x00000000"_view,
	  u8"ALU64 | X     | MOV   .dst=01 .src=02 .off=0x0000 .imm=0x00000000"_view,
	  u8"ALU64 | X     | MOVSX .dst=01 .src=02 .off=0x0008 .imm=0x00000000"_view,
	  u8"ALU64 | X     | MOVSX .dst=01 .src=02 .off=0x0010 .imm=0x00000000"_view,
	  u8"ALU64 | X     | MOVSX .dst=01 .src=02 .off=0x0020 .imm=0x00000000"_view,

	  u8"ALU   | K     | ADD   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU   | K     | MUL   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU   | K     | DIV   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU   | K     | SDIV  .dst=01 .src=00 .off=0x0001 .imm=0xFFFFFFFF"_view,
	  u8"ALU   | K     | MOD   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU   | K     | SMOD  .dst=01 .src=00 .off=0x0001 .imm=0xFFFFFFFF"_view,
	  u8"ALU   | K     | MOV   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU64 | K     | ADD   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU64 | K     | MUL   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU64 | K     | DIV   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU64 | K     | SDIV  .dst=01 .src=00 .off=0x0001 .imm=0xFFFFFFFF"_view,
	  u8"ALU64 | K     | MOD   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"ALU64 | K     | SMOD  .dst=01 .src=00 .off=0x0001 .imm=0xFFFFFFFF"_view,
	  u8"ALU64 | K     | MOV   .dst=01 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,

	  u8"JMP   | K     | JA    .dst=00 .src=00 .off=0xFFFF .imm=0x00000000"_view,
	  u8"JMP   | K     | CALL  .dst=00 .src=00 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"JMP   | K     | CALL  .dst=00 .src=01 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"JMP   | K     | CALL  .dst=00 .src=02 .off=0x0000 .imm=0xFFFFFFFF"_view,
	  u8"JMP   | K     | EXIT  .dst=00 .src=00 .off=0x0000 .imm=0x00000000"_view,

	  u8"JMP   | X     | JEQ   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"JMP   | X     | JGT   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"JMP   | X     | JSET  .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"JMP32 | X     | JEQ   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"JMP32 | X     | JGT   .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,
	  u8"JMP32 | X     | JSET  .dst=01 .src=02 .off=0xFFFF .imm=0x00000000"_view,

	  u8"JMP   | K     | JEQ   .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	  u8"JMP   | K     | JGT   .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	  u8"JMP   | K     | JSET  .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	  u8"JMP32 | K     | JEQ   .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	  u8"JMP32 | K     | JGT   .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	  u8"JMP32 | K     | JSET  .dst=01 .src=00 .off=0xFFFF .imm=0xFFFFFFFF"_view,
	};

	ASSERT_EQUAL(inst.size(), expected.size());

	for (size_t i = 0U; i < expected.size(); ++i)
	{
		ASSERT_EQUAL(lak::u8string(inst[i]), expected[i]);
	}

	return 0;
}
END_TEST()
