lakcore_system_win32 = static_library(
	'lakcore_system_win32',
	[
		'architecture.cpp',
		'file.cpp',
		'page_memory.cpp',
		'process.cpp',
		'profile.cpp',
		'wrapper.cpp',
	],
	override_options: override_options_w3,
	include_directories: lakcore_inc,
	dependencies: [],
	link_args: lakcore_linkargs,
)
