hello_world = "hello world";
aaaaa = 5 * "a";
aaabb = 3 * "a" , 2 * "b";
aaabbcc = 3 * "a" , 2 * "b" , (2 * "c");
aabbaa = 2 * "a" , <2 * "b"> , 2 * "a" $[](lak::u8string_view str){ return str; }$;
whitespace = {?lak::dsl::ascii_whitespace?};
up_to_5_a=5*["a"];
