#include <lak/array.hpp>
#include <lak/codegen/cpp.hpp>
#include <lak/debug.hpp>
#include <lak/dsl/ebnf.hpp>
#include <lak/format.hpp>
#include <lak/span.hpp>
#include <lak/string_view.hpp>
#include <lak/system/file.hpp>

int main(int argc, char **argv)
{
	if (argc < 3) return EXIT_FAILURE;

	lak::debugger.live_output_enabled = true;
	lak::debugger.live_errors_only    = true;

	lak::fs::path source      = argv[1];
	lak::astring header_guard = argv[2];
	lak::array<lak::astring> namespaces;
	lak::astring prefix;
	for (int i = 3; i < argc; ++i)
	{
		namespaces.push_back(argv[i]);
		prefix += argv[i];
		prefix += "::";
	}

	auto src = lak::read_file(source).UNWRAP();

	std::cerr << "input:\n"
	          << lak::u8string_view(lak::span<char8_t>(lak::span(src))) << "\n";

	auto grammar =
	  lak::dsl::ebnf
	    .parse(lak::u8string_view(lak::span<char8_t>(lak::span(src))))
	    .EXPECT("parse failed")
	    .value;

	lak::codegen::cpp_writer strm;

	strm.push_header_guard(lak::strconv<char8_t>(header_guard))
	  .write_comment(u8"AUTOGENERATED BY EBNF2CPP"_view)
	  .write_newline()
	  .write_newline()
	  .write_include_ang(u8"lak/dsl/dsl.hpp"_view)
	  .write_include_ang(u8"lak/dsl/utility.hpp"_view)
	  .write_newline();

	for (const auto &ns : namespaces)
		strm.push_namespace(lak::strconv<char8_t>(ns));

	std::cerr << "\noutput:\n";

	for (const auto &rule : grammar.rules)
	{
		strm.push_variable_declaration(u8"constexpr auto"_view, rule.name)
		  .write_indent_newline();
		if (rule.transform) strm.push_template_call(u8"lak::dsl::transform"_view);

		lak::array<lak::pair<lak::dsl::ebnf_rule_value, size_t>> stack;

		auto indent_str = [&]() { return lak::astring(stack.size(), '\t'); };

		stack.push_back({grammar.rule_values[rule.definition], 0});

		while (!stack.empty())
		{
			auto &[val, index] = stack.back();
			switch (val.type)
			{
				using enum lak::dsl::ebnf_rule_value::value_type;

				case string:
				{
					if (strm.template is_scope<decltype(strm)::template_call_scope>())
						strm.next_template_argument(true);
					strm.push_template_call(u8"lak::dsl::str_literal"_view)
					  .write_string(grammar.strings[val.index], u8"u8"_view)
					  .pop_template_call();
					stack.pop_back();
				}
				break;

				case rule:
					if (strm.template is_scope<decltype(strm)::template_call_scope>())
						strm.next_template_argument(true);
					strm.write(lak::u8string_view(lak::to_u8string(prefix)))
					  .write(grammar.identifiers[val.index]);
					stack.pop_back();
					break;

				case concatenation:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						bool contains_captures = false;
						for (size_t i = 0U; !contains_captures &&
						                    i < grammar.concatenations[val.index].size();
						     ++i)
							if (grammar
							      .rule_values[grammar.concatenations[val.index].begin + i]
							      .type == capture)
								contains_captures = true;
						strm.push_template_call(contains_captures
						                          ? u8"lak::dsl::capture_sequence"_view
						                          : u8"lak::dsl::sequence"_view);
					}
					if (index >= grammar.concatenations[val.index].size())
					{
						strm.pop_template_call();
						stack.pop_back();
					}
					else
					{
						stack.push_back(
						  {grammar.rule_values[grammar.concatenations[val.index].begin +
						                       (index++)],
						   0U});
					}
					break;

				case alternation:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(u8"lak::dsl::disjunction"_view);
					}
					if (index >= grammar.alternations[val.index].size())
					{
						strm.pop_template_call();
						stack.pop_back();
					}
					else
					{
						stack.push_back(
						  {grammar.rule_values[grammar.alternations[val.index].begin +
						                       (index++)],
						   0U});
					}
					break;

				case optional:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(u8"lak::dsl::optional"_view);
						++index;
						stack.push_back(
						  {grammar.rule_values[grammar.optionals[val.index].index], 0U});
					}
					else
					{
						strm.pop_template_call();
						stack.pop_back();
					}
					break;

				case repetition:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(grammar.repetitions[val.index].count
						                          ? u8"lak::dsl::repeat_exact"_view
						                          : u8"lak::dsl::repeat"_view);
						++index;
						stack.push_back(
						  {grammar.rule_values[grammar.repetitions[val.index].index], 0U});
					}
					else
					{
						if (grammar.repetitions[val.index].count)
						{
							strm.next_template_argument().write(
							  lak::fmt<u8"{:d}U">(*grammar.repetitions[val.index].count));
						}
						strm.pop_template_call();
						stack.pop_back();
					}
					break;

				case match_case:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(u8"lak::dsl::match"_view);
						++index;
						stack.push_back(
						  {grammar.rule_values[grammar.match_cases[val.index].condition],
						   0U});
					}
					else if (index == 1U)
					{
						++index;
						stack.push_back(
						  {grammar.rule_values[grammar.match_cases[val.index].matched],
						   0U});
					}
					else
					{
						strm.pop_template_call();
						stack.pop_back();
					}
					break;

				case match_sequence:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(u8"lak::dsl::match_sequence"_view);
					}
					if (index >= grammar.match_sequences[val.index].size())
					{
						strm.pop_template_call();
						stack.pop_back();
					}
					else
					{
						stack.push_back(
						  {grammar.rule_values[grammar.match_sequences[val.index].begin +
						                       (index++)],
						   0U});
					}
					break;

				case grouping:
				{
					lak::dsl::ebnf_rule_value v =
					  grammar.rule_values[grammar.groupings[val.index].index];
					stack.pop_back();
					stack.push_back({v, 0U});
				}
				break;

				case capture:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(u8"lak::dsl::capture"_view);
						++index;
						stack.push_back(
						  {grammar.rule_values[grammar.captures[val.index].index], 0U});
					}
					else
					{
						strm.pop_template_call();
						stack.pop_back();
					}
					break;

				case special:
					if (strm.template is_scope<decltype(strm)::template_call_scope>())
						strm.next_template_argument(true);
					strm.write(grammar.specials[val.index]);
					stack.pop_back();
					break;

				case exception:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(u8"lak::dsl::conjunction"_view);
						++index;
						stack.push_back(
						  {grammar.rule_values[grammar.exceptions[val.index].rule], 0U});
					}
					else if (index == 1U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(u8"lak::dsl::negative_lookahead"_view);
						++index;
						stack.push_back(
						  {grammar.rule_values[grammar.exceptions[val.index].except_rule],
						   0U});
					}
					else
					{
						strm.pop_template_call().pop_template_call();
						stack.pop_back();
					}
					break;

				case positive_lookahead:
					if (index == 0U)
					{
						if (strm.template is_scope<decltype(strm)::template_call_scope>())
							strm.next_template_argument(true);
						strm.push_template_call(u8"lak::dsl::positive_lookahead"_view)
						  .next_template_argument(false)
						  .push_template_call(u8"lak::dsl::as_pure"_view);
						++index;
						stack.push_back(
						  {grammar
						     .rule_values[grammar.positive_lookaheads[val.index].index],
						   0U});
					}
					else
					{
						strm.pop_template_call().pop_template_call();
						stack.pop_back();
					}
					break;

				default: ASSERT_UNREACHABLE();
			}
		}

		if (rule.transform)
		{
			lak::u8string transform =
			  grammar.transforms[grammar.rule_values[*rule.transform].index];
			// strip \r
			transform.erase(lak::stable_partition(transform.begin(),
			                                      transform.end(),
			                                      [](char8_t c)
			                                      { return c != u8'\r'; }),
			                transform.end());

			strm.next_template_argument(false)
			  .write_newline()
			  .write(transform)
			  .pop_template_call();
		}

		strm.pop_declaration().write_newline();
	}

	for (const auto &ns : namespaces)
	{
		(void)ns;
		strm.pop_namespace();
	}

	strm.pop_header_guard();

	ASSERT(strm.scopes.empty());
	ASSERT(strm.preproc_scopes.empty());

	std::cout << lak::strconv<char, char8_t>(strm);

	return EXIT_SUCCESS;
}
