name: Build

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - run: g++ --std=c++20 tools/workflow-matrix/main.cpp -o gen-matrix
      - run: echo $(./gen-matrix)
      - id: matrix
        run: ./gen-matrix >> $GITHUB_OUTPUT
  test:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - if: matrix.os.system == 'windows'
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.os.arch }}
      - if: matrix.os.system == 'windows'
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson ninja

      - if: matrix.os.system == 'ubuntu' && matrix.os.arch == 'x86'
        uses: egor-tensin/setup-gcc@v2
        with:
          version: latest
          platform: ${{ matrix.os.arch }}
      - if: matrix.os.system == 'ubuntu' && startsWith(matrix.os.arch, 'wasm')
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 6.0.0
      - if: matrix.os.system == 'ubuntu'
        run: |
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install meson ninja
          sudo apt install libx11-dev libx11-xcb-dev libxrandr-dev libwayland-dev libcairo2-dev libegl1-mesa-dev libgbm-dev

      - if: matrix.os.system == 'macos'
        run: |
          brew install meson ninja
          echo "CC=$(brew --prefix llvm@20)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@20)/bin/clang++" >> $GITHUB_ENV

      - run: meson setup build --buildtype debugoptimized ${{ matrix.setup_options }}
      - run: meson compile -C build ${{ matrix.target }}
      - if: matrix.run != ''
        run: ${{ matrix.run }}
  push-staging:
    needs: [test]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push staging branch to trunk
        if: github.event_name == 'push'
        run: git switch trunk && git merge --ff-only staging && git push origin trunk
