name: Build

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-12]
        arch: [x86, x64]
        setup-options:
          - -Dlak_enable_tests=true
          - -Dlak_enable_tests=true -Dlak_enable_lua=true -Dlak_enable_stb=true -Dlak_enable_stb_image=true -Dlak_enable_stb_image_write=true
          - -Dlak_enable_tests=true -Dlak_enable_lmdb=true -Dlak_enable_libfive=true
          - -Dlak_enable_tests=true -Dlak_enable_windowing=true -Dsdl2_from_source=true -Dlak_backend=sdl -Dlak_enable_glm=true -Dlak_enable_imgui=true
        exclude:
          - os: ubuntu-20.04
            setup-options: -Dlak_enable_tests=true -Dlak_enable_lmdb=true -Dlak_enable_libfive=true
          - os: macos-12
            arch: x86
          - os: macos-12
            setup-options: -Dlak_enable_tests=true -Dlak_enable_lmdb=true -Dlak_enable_libfive=true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'

      - if: startsWith(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          # toolset: 19
          vsversion: 2022
      - if: startsWith(matrix.os, 'windows')
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson ninja

      - if: startsWith(matrix.os, 'ubuntu')
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: ${{ matrix.arch }}
      - if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo python3 -m pip install --upgrade pip setuptools wheel
          sudo python3 -m pip install meson ninja

      - if: startsWith(matrix.os, 'macos')
        run: |
          brew install meson ninja
          echo "CC=$(brew --prefix llvm@15)/bin/clang CXX=$(brew --prefix llvm@15)/bin/clang++" >> $GITHUB_ENV

      - run: meson setup build --buildtype debugoptimized ${{ matrix.setup-options }}
      - run: meson compile -C build
      - run: build/lak_test --testall
      - run: build/lak_test_bigint_standalone --testall
  push-staging:
    needs: run-tests
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push staging branch to trunk
        if: github.event_name == 'push'
        run: git switch trunk && git merge --ff-only staging && git push origin trunk
