name: Build

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:

jobs:
  build-min-x86-64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 19
          vsversion: 2022
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          setup-options: --buildtype debugoptimized -Dlak_enable_tests=true
          meson-version: 0.63.3
      - run: build/lak_test.exe --testall
      - run: build/lak_test_bigint_standalone.exe --testall
  build-x86-64:
    needs: build-min-x86-64
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 19
          vsversion: 2022
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          setup-options: --buildtype debugoptimized -Dlak_enable_tests=true -Dlak_enable_lmdb=true -Dlak_enable_libfive=true -Dlak_enable_lua=true
          meson-version: 0.63.3
      - run: build/lak_test.exe --testall
      - run: build/lak_test_bigint_standalone.exe --testall
  build-x86:
    needs: build-x86-64
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
          toolset: 19
          vsversion: 2022
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          setup-options: --buildtype debugoptimized -Dlak_enable_tests=true -Dlak_enable_lmdb=true -Dlak_enable_libfive=true -Dlak_enable_lua=true
          meson-version: 0.63.3
      - run: build/lak_test.exe --testall
      - run: build/lak_test_bigint_standalone.exe --testall
