name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - run: g++ --std=c++20 tools/workflow-matrix/release.cpp -o gen-matrix
      - run: echo $(./gen-matrix)
      - id: matrix
        run: ./gen-matrix >> $GITHUB_OUTPUT

  create-release:
    needs: setup
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag: ${{ steps.get_tag.outputs.TAG }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        shell: bash
        id: get_tag
      - uses: softprops/action-gh-release@v3
        id: create_release
        with:
          draft: false
          prerelease: true
          name: lak ${{ github.ref_name }}
          tag_name: ${{ github.ref }}

  build:
    needs: [setup, create-release]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - if: matrix.os.system == 'windows'
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.os.arch }}
      - if: matrix.os.system == 'windows'
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson ninja

      - if: matrix.os.system == 'ubuntu' && matrix.os.arch == 'x86'
        uses: egor-tensin/setup-gcc@v2
        with:
          version: latest
          platform: ${{ matrix.os.arch }}
      - if: matrix.os.system == 'ubuntu' && startsWith(matrix.os.arch, 'wasm')
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 6.0.0
      - if: matrix.os.system == 'ubuntu'
        run: |
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install meson ninja
          sudo apt install libx11-dev libx11-xcb-dev libxrandr-dev libwayland-dev libcairo2-dev libegl1-mesa-dev libgbm-dev

      - if: matrix.os.system == 'macos'
        run: |
          brew install meson ninja
          echo "CC=$(brew --prefix llvm@20)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@20)/bin/clang++" >> $GITHUB_ENV

      - if: matrix.os.system == 'windows'
        run: meson setup build ${{ matrix.setup_options }} -Dprefix="$pwd\install" -Dbindir=bin -Dlibdir=bin -Dlicensedir="share\licenses"
      - if: matrix.os.system != 'windows'
        run: meson setup build ${{ matrix.setup_options }} -Dprefix="$(pwd)/install" -Dlicensedir="share/licenses"
      - run: |
          meson install -C build
          ls install/
          ls install/bin/
          ls install/share/
      - if: matrix.run != ''
        run: |
          ${{ matrix.run }}

      - if: matrix.os.system == 'windows'
        run: |
          Compress-Archive -Path install\bin\*.exe, install\bin\*.dll, install\share -DestinationPath lak-${{ needs.create-release.outputs.tag }}-${{ matrix.os.system }}-${{ matrix.os.arch }}.zip

      - if: matrix.os.system == 'ubuntu' || matrix.os.system == 'macos'
        run: |
          cd install
          tar cfz lak-${{ needs.create-release.outputs.tag }}-${{ matrix.os.system }}-${{ matrix.os.arch }}.tar.gz *
          ls

      - if: matrix.os.system == 'windows'
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          files: lak-${{ needs.create-release.outputs.tag }}-${{ matrix.os.system }}-${{ matrix.os.arch }}.zip

      - if: matrix.os.system == 'ubuntu' || matrix.os.system == 'macos'
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          files: install/bin/lak-${{ needs.create-release.outputs.tag }}-${{ matrix.os.system }}-${{ matrix.os.arch }}.tar.gz
